drop policy "Activities can be inserted by service role" on "public"."activities";
drop policy "Activities can be viewed by owner" on "public"."activities";
drop policy "Tokens can be managed by service role" on "public"."strava_tokens";
drop policy "Users can insert their own data" on "public"."users";
drop policy "Users can update their own data" on "public"."users";
drop policy "Users can view their own data" on "public"."users";
revoke delete on table "public"."activities" from "anon";
revoke insert on table "public"."activities" from "anon";
revoke references on table "public"."activities" from "anon";
revoke select on table "public"."activities" from "anon";
revoke trigger on table "public"."activities" from "anon";
revoke truncate on table "public"."activities" from "anon";
revoke update on table "public"."activities" from "anon";
revoke delete on table "public"."activities" from "authenticated";
revoke insert on table "public"."activities" from "authenticated";
revoke references on table "public"."activities" from "authenticated";
revoke select on table "public"."activities" from "authenticated";
revoke trigger on table "public"."activities" from "authenticated";
revoke truncate on table "public"."activities" from "authenticated";
revoke update on table "public"."activities" from "authenticated";
revoke delete on table "public"."activities" from "service_role";
revoke insert on table "public"."activities" from "service_role";
revoke references on table "public"."activities" from "service_role";
revoke select on table "public"."activities" from "service_role";
revoke trigger on table "public"."activities" from "service_role";
revoke truncate on table "public"."activities" from "service_role";
revoke update on table "public"."activities" from "service_role";
revoke delete on table "public"."strava_tokens" from "anon";
revoke insert on table "public"."strava_tokens" from "anon";
revoke references on table "public"."strava_tokens" from "anon";
revoke select on table "public"."strava_tokens" from "anon";
revoke trigger on table "public"."strava_tokens" from "anon";
revoke truncate on table "public"."strava_tokens" from "anon";
revoke update on table "public"."strava_tokens" from "anon";
revoke delete on table "public"."strava_tokens" from "authenticated";
revoke insert on table "public"."strava_tokens" from "authenticated";
revoke references on table "public"."strava_tokens" from "authenticated";
revoke select on table "public"."strava_tokens" from "authenticated";
revoke trigger on table "public"."strava_tokens" from "authenticated";
revoke truncate on table "public"."strava_tokens" from "authenticated";
revoke update on table "public"."strava_tokens" from "authenticated";
revoke delete on table "public"."strava_tokens" from "service_role";
revoke insert on table "public"."strava_tokens" from "service_role";
revoke references on table "public"."strava_tokens" from "service_role";
revoke select on table "public"."strava_tokens" from "service_role";
revoke trigger on table "public"."strava_tokens" from "service_role";
revoke truncate on table "public"."strava_tokens" from "service_role";
revoke update on table "public"."strava_tokens" from "service_role";
revoke delete on table "public"."users" from "anon";
revoke insert on table "public"."users" from "anon";
revoke references on table "public"."users" from "anon";
revoke select on table "public"."users" from "anon";
revoke trigger on table "public"."users" from "anon";
revoke truncate on table "public"."users" from "anon";
revoke update on table "public"."users" from "anon";
revoke delete on table "public"."users" from "authenticated";
revoke insert on table "public"."users" from "authenticated";
revoke references on table "public"."users" from "authenticated";
revoke select on table "public"."users" from "authenticated";
revoke trigger on table "public"."users" from "authenticated";
revoke truncate on table "public"."users" from "authenticated";
revoke update on table "public"."users" from "authenticated";
revoke delete on table "public"."users" from "service_role";
revoke insert on table "public"."users" from "service_role";
revoke references on table "public"."users" from "service_role";
revoke select on table "public"."users" from "service_role";
revoke trigger on table "public"."users" from "service_role";
revoke truncate on table "public"."users" from "service_role";
revoke update on table "public"."users" from "service_role";
alter table "public"."activities" drop constraint "activities_activity_id_key";
alter table "public"."activities" drop constraint "activities_strava_id_fkey";
alter table "public"."strava_tokens" drop constraint "strava_tokens_strava_id_fkey";
alter table "public"."strava_tokens" drop constraint "strava_tokens_strava_id_key";
alter table "public"."users" drop constraint "users_strava_id_key";
alter table "public"."activities" drop constraint "activities_pkey";
alter table "public"."strava_tokens" drop constraint "strava_tokens_pkey";
alter table "public"."users" drop constraint "users_pkey";
drop index if exists "public"."activities_activity_id_key";
drop index if exists "public"."activities_pkey";
drop index if exists "public"."idx_activities_activity_id";
drop index if exists "public"."idx_activities_start_date";
drop index if exists "public"."idx_activities_strava_id";
drop index if exists "public"."idx_strava_tokens_strava_id";
drop index if exists "public"."idx_users_strava_id";
drop index if exists "public"."strava_tokens_pkey";
drop index if exists "public"."strava_tokens_strava_id_key";
drop index if exists "public"."users_pkey";
drop index if exists "public"."users_strava_id_key";
drop table "public"."activities";
drop table "public"."strava_tokens";
drop table "public"."users";
